language: go
sudo: false
go:
  - tip
install:
  - go version | grep 1.6 || sudo rm -rf /usr/local/go
  - wget https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.6.linux-amd64.tar.gz
  - go version
  - go get golang.org/x/tools/cmd/vet
  - go get -v github.com/golang/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...
script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...
